return {
  "catppuccin/nvim",
  priority = 1000,
  lazy = true,
  name = "catppuccin",
  flavour = "mocha",
  background = {
    light = "latte",
    dark = "mocha",
  },
  transparent_background = true,
  opts = {
    integrations = {
      aerial = true,
      alpha = true,
      cmp = true,
      dashboard = true,
      flash = true,
      gitsigns = true,
      headlines = true,
      illuminate = true,
      indent_blankline = { enabled = true },
      leap = true,
      lsp_trouble = true,
      mason = true,
      markdown = true,
      mini = true,
      native_lsp = {
        enabled = true,
        underlines = {
          errors = { "undercurl" },
          hints = { "undercurl" },
          warnings = { "undercurl" },
          information = { "undercurl" },
        },
      },
      navic = { enabled = true, custom_bg = "lualine" },
      neotest = true,
      neotree = true,
      noice = true,
      notify = true,
      semantic_tokens = true,
      telescope = true,
      treesitter = true,
      treesitter_context = true,
      which_key = true,
      nvim_tree = true,
    },
  },
  --vim.api.nvim_set_hl(2, "Normal", { bg = "none" }),
  --vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" }),

  -- Enable catppuccin colorscheme
  --vim.cmd.colorscheme "catppuccin",
}
